In [ ]:
house = [1, 2 , 3 , 4]
median
,18for i in range (len(house)):
  #print (len(house))
  # print("this house is ",type(house))
  mean = sum(house)/len(house)
  print(mean)
  if (len(house) % 2 == 0):
   house.sort()
   median = len(house)  /  2
  elif(len(house) % 2 != 0):
    house.sort()
    median = (len(house)+1)/2
print(house[median])

2.5
2.5
2.5
2.5

TypeError: list indices must be integers or slices, not float

In [ ]:
import pandas as pd
House_2 = [
    {"AlbarkaLodge" :  "For renting purpose",
     "Tenant" :  20,
     "Rooms" : 9,
    },
     {"BlueHaven" :  "For renting purpose",
     "Tenant" :  70,
     "Rooms" : 60,
    },
     {"lasVegas lodge" :  "For renting purpose",
     "Tenant" :  45,
     "Rooms" : 35,
    },
]
print( House_2 )
tables = pd.DataFrame(House_2)
print(tables.shape)
tables

[{'AlbarkaLodge': 'For renting purpose', 'Tenant': 20, 'Rooms': 9}, {'BlueHaven': 'For renting purpose', 'Tenant': 70, 'Rooms': 60}, {'lasVegas lodge': 'For renting purpose', 'Tenant': 45, 'Rooms': 35}]
(3, 5)

,AlbarkaLodge,Tenant,Rooms,BlueHaven,lasVegas lodge
0,For renting purpose,20,9,NaN,NaN
1,NaN,70,60,For renting purpose,NaN
2,NaN,45,35,NaN,For renting purpose

In [ ]:
import pandas as pd
Khalid = {
    "AlbarkaLodge" :  [
        {
            "Tenant" :  20,
            "Rooms" : 9,
        }
    ],
    "BlueHavenLodge" :  [
        {
            "Tenant" :  70,
            "Rooms" : 60,
        }
    ],

    "LasvegasLodge" :  [
        {
            "Tenant" :  20,
            "Rooms" : 9,
        }
    ],

}
Tabular = pd.DataFrame(Khalid)
print(type(Tabular))
print(Tabular.shape)
#print(Khalid["AlbarkaLodge"])
#print(Khalid.get("AlbarkaLodge"))
Tabular
pd.DataFrame.from_dict(Khalid)

<class 'pandas.core.frame.DataFrame'>
(1, 3)

,AlbarkaLodge,BlueHavenLodge,LasvegasLodge
0,"{'Tenant': 20, 'Rooms': 9}","{'Tenant': 70, 'Rooms': 60}","{'Tenant': 20, 'Rooms': 9}"

In [ ]:
Mad =[]
Mad.append(house)
Mad.sort
print(Mad)

[[1, 2, 3, 4]]

In [ ]:
import pandas as pd
Khalid = {
    "Ayuba": [15,12,13,14,15,15,17],
    "Hamida" : [15,12,13,14,15,15,17],
    "fisayo" :  [15,12,13,14,15,15,17],
    "Ddad" : [15,12,13,14,15,15,17],
}
pd.DataFrame.from_dict(Khalid)

   Ayuba  Hamida  fisayo  Ddad
0     15      15      15    15
1     12      12      12    12
2     13      13      13    13
3     14      14      14    14
4     15      15      15    15
5     15      15      15    15
6     17      17      17    17

In [ ]:
pd.DataFrame.from_dict(Khalid, orient = "Index" , columns =["a", "b", "c", "d", "e", "f", "g"])

         a   b   c   d   e   f   g
Ayuba   15  12  13  14  15  15  17
Hamida  15  12  13  14  15  15  17
fisayo  15  12  13  14  15  15  17
Ddad    15  12  13  14  15  15  17

In [ ]:
#while working with data frames u use and u use df.shape it gives (A,B) where A is the orientation and b is the feature
#whike working with df.info will give us alll the info neded about out vdtata whether some info has been missiing or nt
#while working with df.head() it gives us the first 5 rows of our data in tabular form , default been 5 , but if u put something inside the parenthesis then we can incerease or decrease the value that will be given out
#Assuming you have some data  thta re lost in the process and you wannt to drop then then use df.dropna(inplace = True)
#Assume yiu wanna change from exampple dollar to anpther thing then u use str.replace("$","What u want to replace it with")
#changing data type will require u to use astype(dataType)
#example : df1.dropna(nplace= True)
#df1 ["price list"].str.replace("$", "",regex = False).str.replace(",", "").astype(float).head()
#to split comma sepreated variables df.str.split("," , expand = True)

In [ ]:
import plotly.express as px
#while using the above library , the syntax are
#px.scatter_mapbox(
    the file we are working on

)